//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookOrder = new HashSet<BookOrder>();
            this.BookShipment = new HashSet<BookShipment>();
            this.Department = new HashSet<Department>();
            this.PurchaseReceipt = new HashSet<PurchaseReceipt>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> PublishId { get; set; }
        public Nullable<System.DateTime> DateOfPublish { get; set; }
        public string Author { get; set; }
        public Nullable<int> GenreId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] ImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Publish Publish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrder> BookOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookShipment> BookShipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReceipt> PurchaseReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
