//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.BookOrder = new HashSet<BookOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> ExecutionStageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserId1 { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<System.DateTime> TimeToCome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrder> BookOrder { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual ExecutionStage ExecutionStage { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
