//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipt
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> NumberOfBook { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
